// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBiQM5CvzI9afoSF3JOF3-Dg_OT0PBqlVA',
    appId: '1:32675577369:web:9c5f76b910db1f64c4b488',
    messagingSenderId: '32675577369',
    projectId: 'provider-dcbd7',
    authDomain: 'provider-dcbd7.firebaseapp.com',
    storageBucket: 'provider-dcbd7.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAudZepkJLo9XGL5XedfGb71ycTKaVE4Do',
    appId: '1:32675577369:android:f9ef8ef59e3340efc4b488',
    messagingSenderId: '32675577369',
    projectId: 'provider-dcbd7',
    storageBucket: 'provider-dcbd7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD6k6lpbs2-DJTX9cC9a7Cf5gjkQzw_mp8',
    appId: '1:32675577369:ios:378ebaac8438ee6ec4b488',
    messagingSenderId: '32675577369',
    projectId: 'provider-dcbd7',
    storageBucket: 'provider-dcbd7.appspot.com',
    iosClientId: '32675577369-96luv8n1g1fsnbam64nv4bl7j0kg4tsp.apps.googleusercontent.com',
    iosBundleId: 'com.example.providerApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD6k6lpbs2-DJTX9cC9a7Cf5gjkQzw_mp8',
    appId: '1:32675577369:ios:378ebaac8438ee6ec4b488',
    messagingSenderId: '32675577369',
    projectId: 'provider-dcbd7',
    storageBucket: 'provider-dcbd7.appspot.com',
    iosClientId: '32675577369-96luv8n1g1fsnbam64nv4bl7j0kg4tsp.apps.googleusercontent.com',
    iosBundleId: 'com.example.providerApp',
  );
}
